# 🛡️ NovaPay · EDA
### Synthetic Financial Transaction Data — Fraud Detection

In [12]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/Usuario/Desktop/synthetic_data_RAW.csv")

In [3]:
df.shape

(6362620, 11)

In [4]:
df["isFraud"].value_counts()

isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [5]:
legit = df[df["isFraud"] == 0].sample(n = 265000, random_state = 42)
fraud = df[df["isFraud"] == 1]

In [6]:
df_balanced = pd.concat([legit, fraud]).reset_index(drop = True)

In [7]:
df_balanced["isFraud"].value_counts()

isFraud
0    265000
1      8213
Name: count, dtype: int64

In [8]:
df_balanced.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,162,CASH_OUT,183806.32,C691771226,19391.00,0.00,C1416312719,382572.19,566378.51,0,0
1,137,PAYMENT,521.37,C203378011,0.00,0.00,M42773300,0.00,0.00,0,0
2,179,PAYMENT,3478.18,C1698571270,19853.00,16374.82,M643984524,0.00,0.00,0,0
3,355,PAYMENT,1716.05,C913764937,5769.17,4053.13,M1387429131,0.00,0.00,0,0
4,354,CASH_IN,253129.93,C2017736577,1328499.49,1581629.42,C407484102,2713220.48,2460090.55,0,0

In [9]:
df_balanced = df_balanced.drop(columns = ["step", "isFlaggedFraud"])

In [10]:
df_balanced.head()

,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud
0,CASH_OUT,183806.32,C691771226,19391.00,0.00,C1416312719,382572.19,566378.51,0
1,PAYMENT,521.37,C203378011,0.00,0.00,M42773300,0.00,0.00,0
2,PAYMENT,3478.18,C1698571270,19853.00,16374.82,M643984524,0.00,0.00,0
3,PAYMENT,1716.05,C913764937,5769.17,4053.13,M1387429131,0.00,0.00,0
4,CASH_IN,253129.93,C2017736577,1328499.49,1581629.42,C407484102,2713220.48,2460090.55,0

In [13]:
high_risk_countries = ['KH', 'CN', 'VE', 'CI', 'NG']
low_risk_countries = ['ES', 'US', 'DE', 'FR', 'GB']

df_balanced['ip_country'] = df_balanced['isFraud'].apply(
    lambda x: np.random.choice(high_risk_countries) 
    if (x == 1 and np.random.random() < 0.6) 
    else np.random.choice(low_risk_countries)
)

In [16]:
high_risk_categories = ['crypto', 'electronics']
low_risk_categories = ['grocery', 'restaurant', 'pharmacy', 'fuel', 'transport']

df_balanced['merchant_category'] = df['isFraud'].apply(
    lambda x: np.random.choice(high_risk_categories)
    if (x == 1 and np.random.random() < 0.65)
    else np.random.choice(low_risk_categories)
)

In [17]:
df_balanced.head()

,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,ip_country,merchant_category
0,CASH_OUT,183806.32,C691771226,19391.00,0.00,C1416312719,382572.19,566378.51,0,ES,restaurant
1,PAYMENT,521.37,C203378011,0.00,0.00,M42773300,0.00,0.00,0,GB,grocery
2,PAYMENT,3478.18,C1698571270,19853.00,16374.82,M643984524,0.00,0.00,0,FR,grocery
3,PAYMENT,1716.05,C913764937,5769.17,4053.13,M1387429131,0.00,0.00,0,ES,restaurant
4,CASH_IN,253129.93,C2017736577,1328499.49,1581629.42,C407484102,2713220.48,2460090.55,0,GB,pharmacy

In [ ]:
# df_balanced.to_csv("C:/Users/Usuario/Desktop/the bridge/github/Desafio_Grupo1/data/synthetic_fin_data_CLEAN.csv", index = False)